# Generated by Django 2.2.7 on 2019-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_face_cnefe',
            fields=[
                ('COD_SETOR', models.IntegerField(primary_key=True, serialize=False)),
                ('NUM_QUADRA', models.IntegerField()),
                ('NUM_FACE', models.IntegerField()),
            ],
            options={
                'db_table': '"CNEFEUNIV"."T_FACE_CNEFE"',
            },
        ),
    ]
